# Stage 1 - build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

EXPOSE 5077

COPY . .
RUN dotnet publish -c Release -o /app/publish

# Update the working directory to reset after publishing
WORKDIR /src

# Stage 2 - runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MedSched.Api.dll"]