# Stage 1 - build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

EXPOSE 5077

COPY . .
RUN dotnet publish -c Release -o /app/publish

# Copy the tests directory into the container
COPY ../tests /src/tests

# Run tests
WORKDIR /src/tests/MedSched.Api.UnitTests
RUN dotnet test MedSched.Api.UnitTests.csproj --no-build --verbosity normal

# Ensure the working directory is reset to the API project after running tests
WORKDIR /src

# Stage 2 - runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MedSched.Api.dll"]