services:
  medsched.api:
    build:
      context: ./src/MedSched.Api
      dockerfile: dockerfile
    ports:
      - "80:80"
      - "5077:5077"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - DATABASE_URL=${DATABASE_URL}

  tests:
    build:
      context: .
      dockerfile: tests/MedSched.Api.UnitTests/dockerfile
    depends_on:
      - medsched.api