services:
  medsched.api:
    build:
      context: ./
      dockerfile: src/MedSched.Api/dockerfile
    ports:
      - "80:80"
      - "5077:5077"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PostgresConnection=Host=postgres;Port=5432;Database=MedSchedDb;Username=MedSchedUser;Password=MedSchedPass
      - RENDER_POSTGRES_URL=${RENDER_POSTGRES_URL}
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: MedSchedUser
      POSTGRES_PASSWORD: MedSchedPass
      POSTGRES_DB: MedSchedDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: